### ISSUE TITLE
Don't use `setBoostLevel` for PBR terrain

### ISSUE THREAD

**Issue by cosmic-linden** [secondlife/viewer#1169]
In the glorious future, we get rid of `setBoostLevel`

Tracking and/or removing this state is error-prone and not necessary with the new system.

- [ ] It is simple to remove the "no delete" state for terrain, but other cases of `setBoostLevel` will require more thought
- [ ] For PBR terrain in particular, `setBoostLevel` is currently still needed for PBR terrain due to the minimap being generated CPU-side using the "raw image". i.e. `BOOST_TERRAIN` tells the texture to load the raw image at a resolution that is higher than would be loaded otherwise.
- [ ] Grokking/debugging of the texture system suggests raw images are generated on texture load, even when not needed. We should look at ways to reduce the need for that, as they are an extra burden on memory use.

```[tasklist]
### Tasks
- [ ] https://github.com/secondlife/viewer/issues/1184
- [ ] https://github.com/secondlife/viewer-private/issues/169
```
