### ISSUE TITLE
Inventory Favorites Main Inventory Mockup

### ISSUE THREAD

**Issue by akleshchev** [secondlife/viewer#1300]
### Description

Implement inventory favorites according to provided mockups.
Branch: https://github.com/secondlife/viewer/tree/project/inventory_favorites

![favorites_menu](https://github.com/secondlife/viewer/assets/117672381/00fd43aa-8fc0-4945-a01a-be0054a9943a)
![favorites_main](https://github.com/secondlife/viewer/assets/117672381/42cf7753-adc9-4307-8166-efadf8fae248)

```[tasklist]
### Tasks
- [x] Implement Inventory Favorites Stars
- [x] Implement Context Menu items
- [x] Implement Framework
- [x] Update Places Floater
- [x] Update Settings
- [x] Update Gear Menu Items
- [x] Update inventory Settings
```

**Comment by kylelinden** [comment]
Work on Inventory Favorites in a branch for reviews and then pull into whichever maint makes sense.

**Comment by akleshchev** [comment]
Done in inventory_favorites branch, waiting for other favorite related changes before merging into a proper branch

**Comment by dmytrohproductengine** [comment]
Passed QA.

Verified on the Second Life Release 7.1.12.12258017789 (64bit) on Win10/OSX in the scope of [IQA#414](https://github.com/secondlife/iqa/issues/414).
